package dvdrental;
// Generated 30/03/2017 10:48:32 by Hibernate Tools 4.3.1

/**
 * Aluno generated by hbm2java
 */
public class Aluno implements java.io.Serializable {

    private int ra;
    private String nome;
    private String curso;

    public Aluno() {
    }

    public Aluno(int ra, String nome, String curso) {
        this.ra = ra;
        this.nome = nome;
        this.curso = curso;
    }

    public int getRa() {
        return this.ra;
    }

    public void setRa(int ra) {
        this.ra = ra;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getCurso() {
        return this.curso;
    }

    public void setCurso(String curso) {
        this.curso = curso;
    }

    @Override
    public String toString() {
        return "Aluno{" + "ra=" + this.ra + ", nome=" + this.nome + ", curso=" + this.curso + '}';
    }

    @Override
    public int hashCode() {
        int hash = 666;
        hash = 13 * hash + this.ra;
        hash = 13 * hash + this.nome.hashCode();
        hash = 13 * hash + this.curso.hashCode();

        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }

        Aluno aux = (Aluno) obj;
        if (this.ra != aux.ra) {
            return false;
        }

        if (!this.nome.equals(aux.getNome())) {
            return false;
        }

        return this.curso.equals(aux.getCurso());
    }

    @Override
    public Object clone() {
        return new Aluno(this);
    }

    protected Aluno(Aluno aluno) {
        this.curso = aluno.curso;
        this.nome = aluno.nome;
        this.ra = aluno.ra;
    }
}
